-- =============================================
-- MUNDIALE AMBATO 2026 - COMPLETE DATABASE SETUP
-- Run this ONCE in Supabase SQL Editor
-- =============================================

-- Clear existing data (optional, comment if you want to keep data)
-- TRUNCATE selecciones, jugadores, cromos CASCADE;

-- =============================================
-- 1. INSERT ALL 48 SELECTIONS (SELECCIONES)
-- =============================================
INSERT INTO selecciones (nombre, confederacion, codigo_fifa, grupo, ranking_fifa, participaciones, mejor_resultado) VALUES
('México', 'CONCACAF', 'MEX', 'A', 15, 17, 'Cuartos de final (1970, 1986)'),
('Sudáfrica', 'CAF', 'RSA', 'A', 66, 4, 'Primera fase (1998, 2002, 2010)'),
('Corea del Sur', 'AFC', 'KOR', 'A', 23, 11, 'Semifinales (2002)'),
('República Checa', 'UEFA', 'CZE', 'A', 34, 2, 'Grupos (2006)'),
('Canadá', 'CONCACAF', 'CAN', 'B', 28, 3, 'Octavos de final (2022)'),
('Bosnia y Herzegovina', 'UEFA', 'BIH', 'B', 48, 2, 'Grupos (2014)'),
('Catar', 'AFC', 'QAT', 'B', 44, 2, 'Grupos (2022)'),
('Suiza', 'UEFA', 'SUI', 'B', 19, 12, 'Cuartos de final (1934, 1938, 1954, 2022)'),
('Brasil', 'CONMEBOL', 'BRA', 'C', 5, 22, 'Campeón (1958, 1962, 1970, 1994, 2002)'),
('Marruecos', 'CAF', 'MAR', 'C', 12, 6, 'Semifinales (2022)'),
('Haití', 'CONCACAF', 'HAI', 'C', 83, 1, 'Primera fase (1974)'),
('Escocia', 'UEFA', 'SCO', 'C', 40, 8, 'Grupos (1954, 1958, 1974, 1982, 1986, 1990, 1998, 2022)'),
('Estados Unidos', 'CONCACAF', 'USA', 'D', 16, 11, 'Tercer lugar (1930)'),
('Paraguay', 'CONMEBOL', 'PAR', 'D', 35, 8, 'Cuartos de final (2010)'),
('Australia', 'AFC', 'AUS', 'D', 27, 6, 'Octavos de final (2006, 2022)'),
('Turquía', 'UEFA', 'TUR', 'D', 32, 3, 'Tercer lugar (2002)'),
('Alemania', 'UEFA', 'GER', 'E', 3, 20, 'Campeón (1954, 1974, 1990, 2014)'),
('Curazao', 'CONCACAF', 'CUW', 'E', 91, 1, 'Debutante'),
('Costa de Marfil', 'CAF', 'CIV', 'E', 39, 4, 'Octavos de final (2022)'),
('Ecuador', 'CONMEBOL', 'ECU', 'E', 31, 4, 'Octavos de final (2006)'),
('Países Bajos', 'UEFA', 'NED', 'F', 6, 11, 'Subcampeón (1974, 1978, 2010)'),
('Japón', 'AFC', 'JPN', 'F', 18, 7, 'Octavos de final (2002, 2010, 2018, 2022)'),
('Túnez', 'CAF', 'TUN', 'F', 30, 6, 'Grupos (1978, 1998, 2002, 2006, 2018, 2022)'),
('Suecia', 'UEFA', 'SWE', 'F', 25, 12, 'Subcampeón (1958)'),
('Bélgica', 'UEFA', 'BEL', 'G', 8, 14, 'Tercer lugar (2018)'),
('Egipto', 'CAF', 'EGY', 'G', 37, 3, 'Octavos de final (1934)'),
('Irán', 'AFC', 'IRN', 'G', 24, 6, 'Grupos (1978, 1998, 2006, 2014, 2018, 2022)'),
('Nueva Zelanda', 'OFC', 'NZL', 'G', 98, 2, 'Grupos (1982, 2010)'),
('España', 'UEFA', 'ESP', 'H', 2, 16, 'Campeón (2010)'),
('Cabo Verde', 'CAF', 'CPV', 'H', 69, 1, 'Debutante'),
('Arabia Saudí', 'AFC', 'KSA', 'H', 61, 6, 'Octavos de final (1994)'),
('Uruguay', 'CONMEBOL', 'URU', 'H', 17, 14, 'Campeón (1930, 1950)'),
('Francia', 'UEFA', 'FRA', 'I', 1, 15, 'Campeón (1998, 2018)'),
('Senegal', 'CAF', 'SEN', 'I', 20, 3, 'Cuartos de final (2022)'),
('Irak', 'AFC', 'IRQ', 'I', 55, 1, 'Grupos (1986)'),
('Noruega', 'UEFA', 'NOR', 'I', 26, 3, 'Octavos de final (1998)'),
('Argentina', 'CONMEBOL', 'ARG', 'J', 4, 18, 'Campeón (1978, 1986, 2022)'),
('Argelia', 'CAF', 'ALG', 'J', 42, 4, 'Octavos de final (2014)'),
('Austria', 'UEFA', 'AUT', 'J', 22, 7, 'Tercer lugar (1954)'),
('Jordania', 'AFC', 'JOR', 'J', 58, 1, 'Debutante'),
('Portugal', 'UEFA', 'POR', 'K', 7, 8, 'Tercer lugar (1966)'),
('RD Congo', 'CAF', 'COD', 'K', 52, 1, 'Debutante'),
('Uzbekistán', 'AFC', 'UZB', 'K', 65, 1, 'Debutante'),
('Colombia', 'CONMEBOL', 'COL', 'K', 14, 6, 'Octavos de final (1990, 2014, 2018)'),
('Inglaterra', 'UEFA', 'ENG', 'L', 4, 16, 'Campeón (1966)'),
('Croacia', 'UEFA', 'CRO', 'L', 9, 6, 'Subcampeón (2018)'),
('Ghana', 'CAF', 'GHA', 'L', 38, 4, 'Cuartos de final (2010)'),
('Panamá', 'CONCACAF', 'PAN', 'L', 36, 2, 'Grupos (2018)')
ON CONFLICT (codigo_fifa) DO NOTHING;

-- =============================================
-- 2. INSERT ALL PLAYERS (26 per selection = 1248 total)
-- =============================================

-- MEXICO (id will be 1 if first insert)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Raúl', 'Rangel', 1, 'Portero', 'Chivas', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Guillermo', 'Ochoa', 12, 'Portero', 'AEL Limassol', 39, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Carlos', 'Acevedo', 23, 'Portero', 'Santos', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'César', 'Montes', 2, 'Defensor', 'Lokomotiv Moscú', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Johan', 'Vásquez', 3, 'Defensor', 'Genoa', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Mateo', 'Chávez', 4, 'Defensor', 'AZ Alkmaar', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Jorge', 'Sánchez', 5, 'Defensor', 'PAOK', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Israel', 'Reyes', 13, 'Defensor', 'América', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Jesús', 'Gallardo', 7, 'Defensor', 'Toluca', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Edson', 'Álvarez', 6, 'Centrocampista', 'Fenerbahçe', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Gilberto', 'Mora', 8, 'Centrocampista', 'Tijuana', 17, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Orbelín', 'Pineda', 10, 'Centrocampista', 'AEK Atenas', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Erik', 'Lira', 14, 'Centrocampista', 'Cruz Azul', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Luis', 'Romo', 15, 'Centrocampista', 'Chivas', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Álvaro', 'Fidalgo', 16, 'Centrocampista', 'Betis', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Brian', 'Gutiérrez', 17, 'Centrocampista', 'Chivas', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Guillermo', 'Martínez', 9, 'Delantero', 'Pumas', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Armando', 'González', 11, 'Delantero', 'Chivas', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Alexis', 'Vega', 18, 'Delantero', 'Toluca', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Santiago', 'Giménez', 19, 'Delantero', 'AC Milan', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Raúl', 'Jiménez', 20, 'Delantero', 'Fulham', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Roberto', 'Alvarado', 21, 'Delantero', 'Chivas', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Kevin', 'Álvarez', 2, 'Defensor', 'Roma', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Marcel', 'Ruiz', 8, 'Centrocampista', 'Toluca', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Julián', 'Quiñones', 10, 'Delantero', 'Al-Qadisiyah', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MEX'), 'Ángel', 'Sepúlveda', 9, 'Delantero', 'Pumas', 25, false)
ON CONFLICT DO NOTHING;

-- SOUTH AFRICA
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Ronwen', 'Williams', 1, 'Portero', 'Mamelodi Sundowns', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Ricardo', 'Goss', 12, 'Portero', 'Orlando Pirates', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Sifiso', 'Ngobeni', 23, 'Portero', 'SuperSport United', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Mosa', 'Kekana', 2, 'Defensor', 'Mamelodi Sundowns', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Rivaldo', 'Coetzee', 3, 'Defensor', 'Cape Town City', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Grant', 'Kekana', 4, 'Defensor', 'Mamelodi Sundowns', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Bathusi', 'Aubaas', 5, 'Defensor', 'Mamelodi Sundowns', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Fagrie', 'Lakes', 13, 'Defensor', 'Stellenbosch', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Siyanda', 'Xulu', 14, 'Defensor', 'SuperSport United', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Teboho', 'Mokoena', 6, 'Centrocampista', 'Pirates', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Sphephelo', 'Sithole', 8, 'Centrocampista', 'Kaizer Chiefs', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Thabo', 'Molefe', 10, 'Centrocampista', 'Mamelodi Sundowns', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Njabulo', 'Blom', 15, 'Centrocampista', 'Kaizer Chiefs', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Oswin', 'Appollis', 7, 'Delantero', 'Stellenbosch', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Iqraam', 'Rayners', 9, 'Delantero', 'Cape Town City', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Mohau', 'Nkota', 11, 'Delantero', 'Orlando Pirates', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Lebo', 'Mothiba', 18, 'Delantero', 'Strasbourg', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Elias', 'Mokwana', 19, 'Delantero', 'Mamelodi Sundowns', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Gift', 'Motupa', 17, 'Delantero', 'Mamelodi Sundowns', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Zakhele', 'Lepasa', 16, 'Delantero', 'Chippa United', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Siyabonga', 'Ngezane', 21, 'Defensor', 'Golden Arrows', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Abbubaker', 'Mobara', 22, 'Defensor', 'SuperSport United', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Sipho', 'Mbulelo', 20, 'Centrocampista', 'AmaZulu', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Tshegofatso', 'Mashilo', 24, 'Centrocampista', 'Kaizer Chiefs', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Reeves', 'Fuma', 26, 'Portero', 'Marumo Gallants', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'RSA'), 'Teboho', 'Mokoena', 6, 'Centrocampista', 'Pirates', 26, true)
ON CONFLICT DO NOTHING;

-- SOUTH KOREA
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Kim', 'Seung-gyu', 1, 'Portero', 'Al-Shabab', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Jo', 'Hyeon-woo', 12, 'Portero', 'Ulsan HD', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Lee', 'Chang-geun', 23, 'Portero', 'Daegu FC', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Kim', 'Min-jae', 2, 'Defensor', 'Bayern Múnich', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Kim', 'Jin-su', 3, 'Defensor', 'Jeonbuk Hyundai', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Kim', 'Young-gwon', 4, 'Defensor', 'Ulsan HD', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Jung', 'Seung-hyun', 5, 'Defensor', 'Gimcheon Sangmu', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Seol', 'Young-woo', 13, 'Defensor', 'Ulsan HD', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Lee', 'Ki-je', 14, 'Defensor', 'Suwon Samsung', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Hwang', 'In-beom', 6, 'Centrocampista', 'Feyenoord', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Lee', 'Jae-sung', 8, 'Centrocampista', 'Mainz 05', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Son', 'Heung-min', 10, 'Centrocampista', 'Tottenham', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Jeong', 'Woo-yeong', 15, 'Centrocampista', 'Stuttgart', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Hwang', 'Hee-chan', 7, 'Delantero', 'Wolverhampton', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Cho', 'Gue-sung', 9, 'Delantero', 'Midtjylland', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Lee', 'Kang-in', 11, 'Delantero', 'París Saint-Germain', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Oh', 'Hyeon-gyu', 18, 'Delantero', 'Genk', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Yang', 'Min-hyeok', 17, 'Delantero', 'Tottenham', 19, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Park', 'Jin-seop', 16, 'Defensor', 'Jeonbuk Hyundai', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Hong', 'Chul', 20, 'Centrocampista', 'Ulsan HD', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Kwon', 'Hyeok-kyu', 21, 'Centrocampista', 'Daegu FC', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Um', 'Won-sang', 22, 'Delantero', 'Gangwon FC', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Moon', 'Seon-ho', 24, 'Centrocampista', 'Jeonbuk Hyundai', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Song', 'Bum-keun', 26, 'Portero', 'Jeonbuk Hyundai', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Lee', 'Seung-woo', 19, 'Delantero', 'Jeonbuk Hyundai', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KOR'), 'Kim', 'Tae-hwan', 25, 'Defensor', 'Ulsan HD', 28, false)
ON CONFLICT DO NOTHING;

-- CZECH REPUBLIC
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Jindřich', 'Staňek', 1, 'Portero', 'Slavia Praga', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Matěj', 'Kovář', 12, 'Portero', 'Bayer Leverkusen', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Vít', 'Němeček', 23, 'Portero', 'Sparta Praga', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Tomáš', 'Holeš', 2, 'Defensor', 'Slavia Praga', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'David', 'Zima', 3, 'Defensor', 'Torino', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Václav', 'Jemelka', 4, 'Defensor', 'Sigma Olomouc', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Jaroslav', 'Zelený', 5, 'Defensor', 'Sparta Praga', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'David', 'Jurásek', 13, 'Defensor', 'Benfica', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Ladislav', 'Krejčí', 14, 'Defensor', 'Sparta Praga', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Tomáš', 'Souček', 6, 'Centrocampista', 'West Ham', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Antonín', 'Barák', 8, 'Centrocampista', 'Fiorentina', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Vladimír', 'Coufal', 10, 'Centrocampista', 'West Ham', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Michal', 'Sadílek', 15, 'Centrocampista', 'Twente', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Patrik', 'Schick', 7, 'Delantero', 'Bayer Leverkusen', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Antonín', 'Kučera', 9, 'Delantero', 'Slavia Praga', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Adam', 'Hložek', 11, 'Delantero', 'Bayer Leverkusen', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Mojmír', 'Chytil', 18, 'Delantero', 'Slavia Praga', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Václav', 'Sejk', 17, 'Delantero', 'Sparta Praga', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Ondřej', 'Dostál', 16, 'Defensor', 'Baník Ostrava', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Jan', 'Bořil', 20, 'Centrocampista', 'Slavia Praga', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Alex', 'Král', 21, 'Centrocampista', 'Union Berlin', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Matěj', 'Vydra', 22, 'Delantero', 'Viktoria Plzeň', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Lukáš', 'Masopust', 24, 'Centrocampista', 'Sparta Praga', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Jakub', 'Pesek', 26, 'Delantero', 'Slovan Liberec', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Martin', 'Jedlička', 25, 'Portero', 'Dukla Praga', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CZE'), 'Ondřej', 'Kúdela', 19, 'Defensor', 'Sparta Praga', 30, false)
ON CONFLICT DO NOTHING;

-- CANADA
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Dayne', 'St. Clair', 1, 'Portero', 'Minnesota United', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Maxime', 'Crépeau', 12, 'Portero', 'Portland Timbers', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Tom', 'McGill', 23, 'Portero', 'Brighton', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Alistair', 'Johnston', 2, 'Defensor', 'Celtic', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Kamal', 'Miller', 3, 'Defensor', 'Portland Timbers', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Moïse', 'Bombito', 4, 'Defensor', 'Nice', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Joel', 'Waterman', 5, 'Defensor', 'CF Montréal', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Richie', 'Laryea', 13, 'Defensor', 'Toronto FC', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Samuel', 'Adekugbe', 14, 'Defensor', 'Vancouver Whitecaps', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Stephen', 'Eustáquio', 6, 'Centrocampista', 'Porto', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Tajon', 'Buchanan', 8, 'Centrocampista', 'Inter Milán', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Jonathan', 'Osorio', 10, 'Centrocampista', 'Toronto FC', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Ismaël', 'Koné', 15, 'Centrocampista', 'Marseille', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Mark', 'Anthony-Kamal', 7, 'Delantero', 'LASK', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Jonathan', 'David', 9, 'Delantero', 'Lille', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Cyle', 'Larin', 11, 'Delantero', 'Valladolid', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Lucas', 'Cavallini', 18, 'Delantero', 'Puebla', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Jacen', 'Russell-Rowe', 17, 'Delantero', 'Columbus Crew', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Zac', 'Bomber', 16, 'Defensor', 'CF Montréal', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Scott', 'Kennedy', 20, 'Centrocampista', 'Würzburger Kickers', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Mathieu', 'Choinière', 21, 'Centrocampista', 'CF Montréal', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Jackson', 'Hoppe', 22, 'Delantero', 'San Jose Earthquakes', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Liam', 'Fraser', 24, 'Centrocampista', 'Dallas', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Ali', 'Ahmed', 26, 'Centrocampista', 'Vancouver Whitecaps', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'James', 'Pantemis', 25, 'Portero', 'Portland Timbers', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CAN'), 'Niko', 'Sigur', 19, 'Defensor', 'Orlando City', 24, false)
ON CONFLICT DO NOTHING;

-- BOSNIA AND HERZEGOVINA
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Ibrahim', 'Šehić', 1, 'Portero', 'Samsunspor', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Nikola', 'Vasilj', 12, 'Portero', 'Sturm Graz', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Kenan', 'Piric', 23, 'Portero', 'Sarajevo', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Dennis', 'Bratić', 2, 'Defensor', 'Sarajevo', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Adnan', 'Kovačević', 3, 'Defensor', 'Ferencváros', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Nihad', 'Mujakić', 4, 'Defensor', 'Rijeka', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Adnan', 'Kovačević', 5, 'Defensor', 'Ferencváros', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Sead', 'Kolašinac', 13, 'Defensor', 'Atalanta', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Stjepan', 'Lončar', 14, 'Defensor', 'Rijeka', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Miralem', 'Pjanić', 6, 'Centrocampista', 'Sharjah', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Rade', 'Krunić', 8, 'Centrocampista', 'Milan', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Edin', 'Višća', 10, 'Centrocampista', 'Başakşehir', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Ivan', 'Benedik', 15, 'Centrocampista', 'Sarajevo', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Edin', 'Džeko', 7, 'Delantero', 'Fenerbahçe', 38, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Smail', 'Prevljak', 9, 'Delantero', 'Red Bull Salzburg', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Ermedin', 'Demirović', 11, 'Delantero', 'Stuttgart', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Amir', 'Rahmanović', 18, 'Delantero', 'Sarajevo', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Armin', 'Gigović', 17, 'Centrocampista', 'Helsingborg', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Amar', 'Dedić', 16, 'Defensor', 'Wolfsberger', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Haris', 'Hajdarević', 20, 'Centrocampista', 'Željezničar', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Amar', 'Beganović', 21, 'Centrocampista', 'Sarajevo', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Kenan', 'Kodro', 22, 'Delantero', 'Osasuna', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Goran', 'Zara', 24, 'Centrocampista', 'Velež', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Nedim', 'Bulić', 26, 'Portero', 'Posušje', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Dario', 'Saric', 19, 'Centrocampista', 'Osijek', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BIH'), 'Marko', 'Marić', 25, 'Portero', 'Rijeka', 27, false)
ON CONFLICT DO NOTHING;

-- QATAR
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Saad', 'Al-Sheeb', 1, 'Portero', 'Al-Sadd', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Meshaal', 'Barsham', 12, 'Portero', 'Al-Sadd', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Yousef', 'Hassan', 23, 'Portero', 'Al-Gharafa', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Pedro', 'Miguel', 2, 'Defensor', 'Al-Sadd', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Abdelkarim', 'Hassan', 3, 'Defensor', 'Al-Sadd', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Bassam', 'Al-Rawi', 4, 'Defensor', 'Al-Wakrah', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Tarek', 'Salman', 5, 'Defensor', 'Al-Sadd', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Homam', 'Ahmed', 13, 'Defensor', 'Al-Duhail', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Musab', 'Khidir', 14, 'Defensor', 'Al-Wakrah', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Hassan', 'Al-Haydos', 6, 'Centrocampista', 'Al-Sadd', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Abdulaziz', 'Hatem', 8, 'Centrocampista', 'Al-Rayyan', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Akram', 'Afif', 10, 'Centrocampista', 'Al-Sadd', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Salem', 'Al-Dosari', 15, 'Centrocampista', 'Al-Sadd', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Almoez', 'Ali', 7, 'Delantero', 'Al-Duhail', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Mohammed', 'Muntari', 9, 'Delantero', 'Al-Duhail', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Ahmed', 'Alaaeldin', 11, 'Delantero', 'Al-Rayyan', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Yusuf', 'Abdurisag', 18, 'Delantero', 'Al-Sadd', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Khalid', 'Muneer', 17, 'Delantero', 'Al-Wakrah', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Jassem', 'Gabr', 16, 'Defensor', 'Al-Arabi', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Karim', 'Boudiaf', 20, 'Centrocampista', 'Al-Duhail', 34, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Naif', 'Al-Hadhrami', 21, 'Centrocampista', 'Al-Sailiya', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Hassan', 'Palang', 22, 'Delantero', 'Al-Markhiya', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Ali', 'Boudiaf', 24, 'Centrocampista', 'Al-Rayyan', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Ahmed', 'Suhail', 26, 'Portero', 'Al-Wakrah', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Mostafa', 'Tarek', 19, 'Defensor', 'Al-Sadd', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'QAT'), 'Abdulla', 'Ali', 25, 'Delantero', 'Al-Ahli', 24, false)
ON CONFLICT DO NOTHING;

-- SWITZERLAND
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Yann', 'Sommer', 1, 'Portero', 'Inter Milán', 35, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Gregor', 'Kobel', 12, 'Portero', 'Borussia Dortmund', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Anthony', 'Racioppi', 23, 'Portero', 'Young Boys', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Manuel', 'Akanji', 2, 'Defensor', 'Manchester City', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Silvan', 'Widmer', 3, 'Defensor', 'Mainz 05', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Nico', 'Elvedi', 4, 'Defensor', 'Mönchengladbach', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Edimilson', 'Fernandes', 5, 'Defensor', 'Mainz 05', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Ricardo', 'Rodríguez', 13, 'Defensor', 'Torino', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Kevin', 'Mbabu', 14, 'Defensor', 'Servette', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Granit', 'Xhaka', 6, 'Centrocampista', 'Bayer Leverkusen', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Xherdan', 'Shaqiri', 8, 'Centrocampista', 'Chicago Fire', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Remo', 'Freuler', 10, 'Centrocampista', 'Bologna', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Denis', 'Zakaria', 15, 'Centrocampista', 'Monaco', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Breel', 'Embolo', 7, 'Delantero', 'Monaco', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Haris', 'Seferovic', 9, 'Delantero', 'Al-Wasl', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Noah', 'Okafor', 11, 'Delantero', 'Milan', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Ruben', 'Vargas', 18, 'Delantero', 'Augsburg', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Dan', 'Ndoye', 17, 'Delantero', 'Bologna', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Fabian', 'Rieder', 16, 'Centrocampista', 'Young Boys', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Vincent', 'Sierro', 20, 'Centrocampista', 'Young Boys', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Michel', 'Aebischer', 21, 'Centrocampista', 'Bologna', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Zeki', 'Am''douni', 22, 'Delantero', 'Burnley', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Ardon', 'Jashari', 24, 'Centrocampista', 'Young Boys', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Leonardo', 'Bertone', 26, 'Centrocampista', 'Aarau', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Philipp', 'Köhn', 25, 'Portero', 'Montpellier', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SUI'), 'Cédric', 'Zesiger', 19, 'Defensor', 'Augsburg', 26, false)
ON CONFLICT DO NOTHING;

-- BRAZIL
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Alisson', 'Becker', 1, 'Portero', 'Liverpool', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Ederson', 'Moraes', 12, 'Portero', 'Manchester City', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Lucas', 'Perri', 23, 'Portero', 'Lyon', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Marquinhos', 'Santos', 2, 'Defensor', 'París Saint-Germain', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Thiago', 'Silva', 3, 'Defensor', 'Chelsea', 39, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Gabriel', 'Magalhães', 4, 'Defensor', 'Arsenal', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Alex', 'Sandro', 5, 'Defensor', 'Flamengo', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Danilo', 'Luiz', 13, 'Defensor', 'Juventus', 33, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Gleison', 'Bremer', 14, 'Defensor', 'Juventus', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Casemiro', 'Santos', 6, 'Centrocampista', 'Manchester United', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Vinícius', 'Júnior', 8, 'Centrocampista', 'Real Madrid', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Neymar', 'Júnior', 10, 'Centrocampista', 'Al-Hilal', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Bruno', 'Guimarães', 15, 'Centrocampista', 'Newcastle', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Rodrygo', 'Silva', 7, 'Delantero', 'Real Madrid', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Richarlison', 'Oliveira', 9, 'Delantero', 'Tottenham', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Raphinha', 'Dias', 11, 'Delantero', 'Barcelona', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Endrick', 'Felipe', 18, 'Delantero', 'Real Madrid', 18, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Gabriel', 'Jesus', 17, 'Delantero', 'Arsenal', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Joelinton', 'Cavalcanti', 16, 'Centrocampista', 'Newcastle', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Lucas', 'Paquetá', 20, 'Centrocampista', 'West Ham', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'André', 'Trindade', 21, 'Centrocampista', 'Fluminense', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Martinelli', 'Silva', 22, 'Delantero', 'Arsenal', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Weverton', 'Pereira', 24, 'Portero', 'Palmeiras', 36, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Eder', 'Militão', 19, 'Defensor', 'Real Madrid', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Douglas', 'Luiz', 25, 'Centrocampista', 'Aston Villa', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BRA'), 'Savio', 'Moreira', 26, 'Delantero', 'Girona', 20, false)
ON CONFLICT DO NOTHING;

-- MOROCCO
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Yassine', 'Bounou', 1, 'Portero', 'Al-Hilal', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Munir', 'Mohamedi', 12, 'Portero', 'Al-Wehda', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Mehdi', 'Benabid', 23, 'Portero', 'FUS Rabat', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Achraf', 'Hakimi', 2, 'Defensor', 'París Saint-Germain', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Nayef', 'Aguerd', 3, 'Defensor', 'Real Sociedad', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Sofyan', 'Amrabat', 4, 'Defensor', 'Fiorentina', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Noussair', 'Mazraoui', 5, 'Defensor', 'Bayern Múnich', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Yahia', 'Attiyat-Allah', 13, 'Defensor', 'Al-Ahly', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Hakim', 'Ziyech', 14, 'Defensor', 'Al-Duhail', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Amir', 'Richardson', 6, 'Centrocampista', 'Wolverhampton', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Azzedine', 'Ounahi', 8, 'Centrocampista', 'Marseille', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Sofiane', 'Boufal', 10, 'Centrocampista', 'Angers', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Selim', 'Amallah', 15, 'Centrocampista', 'Valencia', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Youssef', 'En-Nesyri', 7, 'Delantero', 'Fenerbahçe', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Tarik', 'Tissoudali', 9, 'Delantero', 'Gent', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Abde', 'Ezzalzouli', 11, 'Delantero', 'Real Betis', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Amine', 'Adli', 18, 'Delantero', 'Toulouse', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Ismael', 'Saibari', 17, 'Delantero', 'PSV', 22, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Bilal', 'El Khannous', 16, 'Centrocampista', 'Genk', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Imran', 'Louza', 20, 'Centrocampista', 'Nantes', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Ayoub', 'El Kaabi', 21, 'Delantero', 'Olympiacos', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Hamza', 'Igamane', 22, 'Delantero', 'Rangers', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Jawad', 'El Yamiq', 24, 'Defensor', 'Al-Wakrah', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Mohamed', 'Chibi', 26, 'Centrocampista', 'Wydad', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Reda', 'Belahyane', 25, 'Centrocampista', 'Montpellier', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'MAR'), 'Guy', 'Mfulu', 19, 'Centrocampista', 'Clermont', 27, false)
ON CONFLICT DO NOTHING;

-- HAITI
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Alexandre', 'Pierre', 1, 'Portero', 'Violette', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Jean', 'Gardy', 12, 'Portero', 'Cavaly', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Reginald', 'Metellus', 23, 'Portero', 'Don Bosco', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Ricardo', 'Adé', 2, 'Defensor', 'Violette', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Alex', 'Christian', 3, 'Defensor', 'Dunkerque', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Carlens', 'Arcan', 4, 'Defensor', 'Cavaly', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Sébastien', 'Théresa', 5, 'Defensor', 'Violette', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Steven', 'Fortune', 13, 'Defensor', 'Baltimore', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Luckson', 'Augustin', 14, 'Defensor', 'Don Bosco', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Bryan', 'Alcéus', 6, 'Centrocampista', 'Violette', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Dany', 'Jean', 8, 'Centrocampista', 'Columbus Crew', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Hérold', 'Charles', 10, 'Centrocampista', 'Violette', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Jonel', 'Désiré', 15, 'Centrocampista', 'Cavaly', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Frantzdy', 'Pierrot', 7, 'Delantero', 'Guingamp', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Duckens', 'Nazon', 9, 'Delantero', 'Konyaspor', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Carnejy', 'Antoine', 11, 'Delantero', 'Bastia', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Mikaël', 'Cantave', 18, 'Delantero', 'Violette', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Kervens', 'Jolitte', 17, 'Delantero', 'Don Bosco', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Daniel', 'Baptiste', 16, 'Centrocampista', 'Baltimore', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Claude', 'Duclervil', 20, 'Centrocampista', 'Cavaly', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Odelice', 'Haird', 21, 'Delantero', 'Violette', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Watson', 'Nordé', 22, 'Delantero', 'Baltimore', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Jeremy', 'Nazaire', 24, 'Centrocampista', 'Don Bosco', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Roobens', 'Augustin', 26, 'Portero', 'Cavaly', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Jeff', 'Laurore', 19, 'Defensor', 'Violette', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'HAI'), 'Valens', 'Altidor', 25, 'Defensor', 'Cavaly', 28, false)
ON CONFLICT DO NOTHING;

-- SCOTLAND
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Craig', 'Gordon', 1, 'Portero', 'Heart of Midlothian', 40, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Angus', 'Gunn', 12, 'Portero', 'Norwich City', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Liam', 'Kelly', 23, 'Portero', 'Motherwell', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Andrew', 'Robertson', 2, 'Defensor', 'Liverpool', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Kieran', 'Tierney', 3, 'Defensor', 'Arsenal', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Scott', 'McTominay', 4, 'Defensor', 'Napoli', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Grant', 'Hanley', 5, 'Defensor', 'Norwich City', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Aaron', 'Hickey', 13, 'Defensor', 'Brentford', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Liam', 'Cooper', 14, 'Defensor', 'Leeds United', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Callum', 'McGregor', 6, 'Centrocampista', 'Celtic', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'John', 'McGinn', 8, 'Centrocampista', 'Aston Villa', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Ryan', 'Christie', 10, 'Centrocampista', 'Bournemouth', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Kenny', 'McLean', 15, 'Centrocampista', 'Norwich City', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Che', 'Adams', 7, 'Delantero', 'Torino', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Lyndon', 'Dykes', 9, 'Delantero', 'Queens Park Rangers', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Stuart', 'Armstrong', 11, 'Delantero', 'Southampton', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Ben', 'Doak', 18, 'Delantero', 'Middlesbrough', 19, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Tommy', 'Conlon', 17, 'Centrocampista', 'Celtic', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Max', 'Johnston', 16, 'Defensor', 'Sturm Graz', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Billy', 'Gilmour', 20, 'Centrocampista', 'Brighton', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Ryan', 'Gauld', 21, 'Centrocampista', 'Vancouver Whitecaps', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Kevin', 'Nisbet', 22, 'Delantero', 'Aberdeen', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Kasper', 'Schmeichel', 24, 'Portero', 'Anderlecht', 37, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Ross', 'Stewart', 26, 'Delantero', 'Southampton', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Scott', 'McKenna', 19, 'Defensor', 'Copenhagen', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SCO'), 'Nathan', 'Patterson', 25, 'Defensor', 'Everton', 22, false)
ON CONFLICT DO NOTHING;

-- UNITED STATES
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Matt', 'Turner', 1, 'Portero', 'Crystal Palace', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Ethan', 'Horvath', 12, 'Portero', 'Cardiff City', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Gabriel', 'Slonina', 23, 'Portero', 'Chelsea', 20, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Sergiño', 'Dest', 2, 'Defensor', 'PSV', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Chris', 'Richards', 3, 'Defensor', 'Crystal Palace', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Tyler', 'Adams', 4, 'Defensor', 'Bournemouth', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Antonee', 'Robinson', 5, 'Defensor', 'Fulham', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Timothy', 'Weah', 13, 'Defensor', 'Juventus', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Auston', 'Trusty', 14, 'Defensor', 'Sheffield United', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Weston', 'McKennie', 6, 'Centrocampista', 'Juventus', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Giovanni', 'Reyna', 8, 'Centrocampista', 'Borussia Dortmund', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Christian', 'Pulisic', 10, 'Centrocampista', 'AC Milan', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Yunus', 'Musah', 15, 'Centrocampista', 'AC Milan', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Tim', 'Weah', 7, 'Delantero', 'Juventus', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Ricardo', 'Pepi', 9, 'Delantero', 'PSV', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Folarin', 'Balogun', 11, 'Delantero', 'Monaco', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Alejandro', 'Zendejas', 18, 'Delantero', 'América', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Haji', 'Wright', 17, 'Delantero', 'Montpellier', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Cristian', 'Roldán', 16, 'Centrocampista', 'Seattle Sounders', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Brenden', 'Aaronson', 20, 'Centrocampista', 'Leeds United', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'John', 'McVey', 21, 'Centrocampista', 'New York City', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Jordan', 'Pefok', 22, 'Delantero', 'Borussia Mönchengladbach', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Luca', 'de la Torre', 24, 'Centrocampista', 'Celta Vigo', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Mark', 'McKenzie', 19, 'Defensor', 'Genk', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Djordje', 'Mihailovic', 25, 'Centrocampista', 'Colorado Rapids', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'USA'), 'Mike', 'Magee', 26, 'Delantero', 'Retired', 39, false)
ON CONFLICT DO NOTHING;

-- PARAGUAY
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Carlos', 'Fernández', 1, 'Portero', 'Olimpia', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Gatito', 'Fernández', 12, 'Portero', 'Botafogo', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Alfredo', 'Agüero', 23, 'Portero', 'Libertad', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Gustavo', 'Gómez', 2, 'Defensor', 'Palmeiras', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Omar', 'Alderete', 3, 'Defensor', 'Getafe', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Fabrizio', 'Peralta', 4, 'Defensor', 'Cerro Porteño', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Matías', 'Galarza', 5, 'Defensor', 'Argentinos Juniors', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Santiago', 'Arzamendia', 13, 'Defensor', 'Cerro Porteño', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Iván', 'Piris', 14, 'Defensor', 'Libertad', 35, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Mathías', 'Villaseñor', 6, 'Centrocampista', 'Olimpia', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Miguel', 'Almirón', 8, 'Centrocampista', 'Newcastle', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Julio', 'Enciso', 10, 'Centrocampista', 'Brighton', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Andrés', 'Cubas', 15, 'Centrocampista', 'Lille', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Ángel', 'Romero', 7, 'Delantero', 'Toluca', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Adam', 'Bareiro', 9, 'Delantero', 'San Lorenzo', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Gabriel', 'Ávalos', 11, 'Delantero', 'Independiente', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Carlos', 'González', 18, 'Delantero', 'Olimpia', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Diego', 'Gómez', 17, 'Centrocampista', 'Real Betis', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Richard', 'Sánchez', 16, 'Centrocampista', 'Talleres', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Hernesto', 'Caballero', 20, 'Centrocampista', 'Olimpia', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Mathías', 'Rojas', 21, 'Delantero', 'Cruzeiro', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Antonio', 'Sanabria', 22, 'Delantero', 'Torino', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Blas', 'Cáceres', 24, 'Defensor', 'Libertad', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Rodrigo', 'Morínigo', 26, 'Portero', 'Guaraní', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Néstor', 'Giménez', 19, 'Centrocampista', 'Emelec', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'PAR'), 'Juan', 'Iturbe', 25, 'Delantero', 'Cerro Porteño', 31, false)
ON CONFLICT DO NOTHING;

-- AUSTRALIA
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Mathew', 'Ryan', 1, 'Portero', 'AZ Alkmaar', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Tom', 'Glover', 12, 'Portero', 'Melbourne City', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Joe', 'Gauci', 23, 'Portero', 'Adelaide United', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Milos', 'Degenek', 2, 'Defensor', 'Columbus Crew', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Kye', 'Rowles', 3, 'Defensor', 'Hearts', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Curtis', 'Good', 4, 'Defensor', 'Newcastle Jets', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Jordan', 'Bos', 5, 'Defensor', 'Westerlo', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Aziz', 'Behich', 13, 'Defensor', 'Melbourne City', 33, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Fran', 'Karačić', 14, 'Defensor', 'Brescia', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Jackson', 'Irvine', 6, 'Centrocampista', 'St. Pauli', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Konstantinos', 'Mavropanos', 8, 'Centrocampista', 'West Ham', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Ajdin', 'Hrustic', 10, 'Centrocampista', 'Hertha BSC', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Keanu', 'Baccus', 15, 'Centrocampista', 'St. Mirren', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Martin', 'Boyle', 7, 'Delantero', 'Hibernian', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Mitchell', 'Duke', 9, 'Delantero', 'Auckland FC', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Kusini', 'Yengi', 11, 'Delantero', 'Portsmouth', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'John', 'Iredale', 18, 'Delantero', 'FC Seoul', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Nestory', 'Irankunda', 17, 'Delantero', 'Bayern Múnich II', 19, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Aiden', 'O''Neill', 16, 'Centrocampista', 'Charlotte FC', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Riley', 'McGree', 20, 'Centrocampista', 'Middlesbrough', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Patrick', 'Yazbek', 21, 'Centrocampista', 'Western Sydney', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Samuel', 'Silvera', 22, 'Delantero', 'Portsmouth', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Alexander', 'Grant', 24, 'Defensor', 'Perth Glory', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Cameron', 'Burgess', 19, 'Defensor', 'Ipswich Town', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Danny', 'Vukovic', 25, 'Portero', 'Retired', 39, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'AUS'), 'Ryan', 'Teague', 26, 'Centrocampista', 'Melbourne Victory', 24, false)
ON CONFLICT DO NOTHING;

-- TURKEY
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Altay', 'Bayındır', 1, 'Portero', 'Manchester United', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Uğurcan', 'Çakır', 12, 'Portero', 'Trabzonspor', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Mert', 'Günok', 23, 'Portero', 'Beşiktaş', 35, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Mert', 'Müldür', 2, 'Defensor', 'Sassuolo', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Merih', 'Demiral', 3, 'Defensor', 'Al-Ahli', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Samet', 'Akaydın', 4, 'Defensor', 'Trabzonspor', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Abdülkerim', 'Bardakcı', 5, 'Defensor', 'Galatasaray', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Ferdi', 'Kadıoğlu', 13, 'Defensor', 'Fenerbahçe', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Eren', 'Elmalı', 14, 'Defensor', 'Trabzonspor', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Salih', 'Özcan', 6, 'Centrocampista', 'Borussia Dortmund', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Kerem', 'Aktürkoğlu', 8, 'Centrocampista', 'Benfica', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Hakan', 'Çalhanoğlu', 10, 'Centrocampista', 'Inter Milán', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Berat', 'Özdemir', 15, 'Centrocampista', 'Sassuolo', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Cengiz', 'Ünder', 7, 'Delantero', 'Fenerbahçe', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Enes', 'Ünal', 9, 'Delantero', 'Real Sociedad', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'İrfan', 'Can', 11, 'Delantero', 'Borussia Dortmund', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Bertuğ', 'Yıldırım', 18, 'Delantero', 'Trabzonspor', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Yusuf', 'Sarı', 17, 'Delantero', 'Fenerbahçe', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'İsmail', 'Yüksek', 16, 'Centrocampista', 'Fenerbahçe', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Orkun', 'Kökçü', 20, 'Centrocampista', 'Benfica', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Arda', 'Güler', 21, 'Centrocampista', 'Real Madrid', 19, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Kenan', 'Yıldız', 22, 'Delantero', 'Juventus', 19, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Zeki', 'Çelik', 24, 'Defensor', 'Roma', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Bartuğ', 'Elmaz', 26, 'Centrocampista', 'Napoli', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Volkan', 'Babacan', 25, 'Portero', 'Başakşehir', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUR'), 'Emre', 'Bilgin', 19, 'Centrocampista', 'Beşiktaş', 23, false)
ON CONFLICT DO NOTHING;

-- GERMANY
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Manuel', 'Neuer', 1, 'Portero', 'Bayern Múnich', 38, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Marc-André', 'ter Stegen', 12, 'Portero', 'Barcelona', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Oliver', 'Baumann', 23, 'Portero', 'Hoffenheim', 34, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Antonio', 'Rüdiger', 2, 'Defensor', 'Real Madrid', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Matthias', 'Ginter', 3, 'Defensor', 'Mönchengladbach', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Jonathan', 'Tah', 4, 'Defensor', 'Bayer Leverkusen', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Maximilian', 'Mittelstädt', 5, 'Defensor', 'Stuttgart', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Joshua', 'Kimmich', 13, 'Defensor', 'Bayern Múnich', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Nico', 'Schlotterbeck', 14, 'Defensor', 'Borussia Dortmund', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Toni', 'Kroos', 6, 'Centrocampista', 'Retired', 34, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Florian', 'Wirtz', 8, 'Centrocampista', 'Bayer Leverkusen', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Jamal', 'Musiala', 10, 'Centrocampista', 'Bayern Múnich', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Emre', 'Can', 15, 'Centrocampista', 'Borussia Dortmund', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Leroy', 'Sané', 7, 'Delantero', 'Bayern Múnich', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Niclas', 'Füllkrug', 9, 'Delantero', 'Borussia Dortmund', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Thomas', 'Müller', 11, 'Delantero', 'Bayern Múnich', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Kai', 'Havertz', 18, 'Delantero', 'Arsenal', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Karim', 'Adeyemi', 17, 'Delantero', 'Borussia Dortmund', 22, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'İlkay', 'Gündoğan', 16, 'Centrocampista', 'Manchester City', 33, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Chris', 'Führich', 20, 'Centrocampista', 'Stuttgart', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Deniz', 'Undav', 21, 'Delantero', 'Stuttgart', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Robin', 'Gosens', 22, 'Defensor', 'Union Berlin', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Waldemar', 'Anton', 24, 'Defensor', 'Stuttgart', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Alexander', 'Nübel', 19, 'Portero', 'Stuttgart', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Leon', 'Goretzka', 25, 'Centrocampista', 'Bayern Múnich', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'GER'), 'Benjamin', 'Henrichs', 26, 'Defensor', 'RB Leipzig', 27, false)
ON CONFLICT DO NOTHING;

-- CURACAO
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Eloy', 'Room', 1, 'Portero', 'Go Ahead Eagles', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Ricardo', 'Santos', 12, 'Portero', 'USV', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Nigel', 'Sint Jago', 23, 'Portero', 'Inter Willemstad', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Cuco', 'Martina', 2, 'Defensor', 'NEC', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Darryl', 'Lachman', 3, 'Defensor', 'PEC Zwolle', 35, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Roshon', 'van Eijma', 4, 'Defensor', 'MVV Maastricht', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Shanon', 'Carmelia', 5, 'Defensor', 'Helmond Sport', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Juriën', 'Gaari', 13, 'Defensor', 'RKC Waalwijk', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Ayrton', 'Statie', 14, 'Defensor', 'Telstar', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Jeremy', 'Antonia', 6, 'Centrocampista', 'De Graafschap', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Leandro', 'Bacuna', 8, 'Centrocampista', 'Cardiff City', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Juninho', 'Bacuna', 10, 'Centrocampista', 'Preston North End', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Kenji', 'Gorré', 15, 'Centrocampista', 'ADO Den Haag', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Brandley', 'Kuwas', 7, 'Delantero', 'Enosis Neon', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Jafar', 'Arias', 9, 'Delantero', 'PEC Zwolle', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Rangelo', 'Janga', 11, 'Delantero', 'AZ Alkmaar', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Gervane', 'Kastaneer', 18, 'Delantero', 'Heracles', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Jürgen', 'Locadia', 17, 'Delantero', 'Fortuna Sittard', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Nathan', 'de Jong', 16, 'Centrocampista', 'Roda JC', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Lazarus', 'Dauwe', 20, 'Centrocampista', 'MVV Maastricht', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Jearl', 'Marugg', 21, 'Delantero', 'VVV-Venlo', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Javier', 'Erasmus', 22, 'Delantero', 'Telstar', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Juriën', 'Kemper', 24, 'Defensor', 'ADO Den Haag', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Luis', 'Bachu', 26, 'Portero', 'Inter Willemstad', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Michaël', 'Murillo', 19, 'Defensor', 'De Graafschap', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CUW'), 'Giandro', 'Sambo', 25, 'Centrocampista', 'Helmond Sport', 26, false)
ON CONFLICT DO NOTHING;

-- IVORY COAST
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Yahia', 'Fofana', 1, 'Portero', 'Lens', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Badra', 'Ali', 12, 'Portero', 'ASEC Mimosas', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Charles', 'Folly', 23, 'Portero', 'FC San Pedro', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Serge', 'Aurier', 2, 'Defensor', 'Nottingham Forest', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Eric', 'Bailly', 3, 'Defensor', 'Beşiktaş', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Willy', 'Boly', 4, 'Defensor', 'Nottingham Forest', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Odilon', 'Kossounou', 5, 'Defensor', 'Leverkusen', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Ghislain', 'Konan', 13, 'Defensor', 'Reims', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Moustapha', 'Diallo', 14, 'Defensor', 'Nantes', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Franck', 'Kessié', 6, 'Centrocampista', 'Al-Ahli', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Hamed', 'Traoré', 8, 'Centrocampista', 'Bournemouth', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Jean-Michaël', 'Serí', 10, 'Centrocampista', 'Hull City', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Ibrahim', 'Sangaré', 15, 'Centrocampista', 'Nottingham Forest', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Nicolas', 'Pépé', 7, 'Delantero', 'Trabzonspor', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Sébastien', 'Haller', 9, 'Delantero', 'Borussia Dortmund', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Karim', 'Konaté', 11, 'Delantero', 'Red Bull Salzburg', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Christian', 'Koffi', 18, 'Delantero', 'Slavia Praga', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Simon', 'Adingra', 17, 'Delantero', 'Brighton', 22, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Ismaël', 'Diallo', 16, 'Defensor', 'Marseille', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Cédric', 'Kipré', 20, 'Defensor', 'Charlton Athletic', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Jean-Philippe', 'Krass', 21, 'Centrocampista', 'Brest', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Emmanuel', 'Latte', 22, 'Delantero', 'Molde', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Idrissa', 'Doumbia', 24, 'Centrocampista', 'Westerlo', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Sylvain', 'Gbohouo', 25, 'Portero', 'ASEC Mimosas', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Mamadou', 'Sangaré', 19, 'Centrocampista', 'Young Boys', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CIV'), 'Kader', 'Keïta', 26, 'Delantero', 'SønderjyskE', 25, false)
ON CONFLICT DO NOTHING;

-- ECUADOR
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Moisés', 'Ramírez', 1, 'Portero', 'Independiente', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Gonzalo', 'Valle', 12, 'Portero', 'Emelec', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Leonardo', 'Realpe', 23, 'Portero', 'LDU Quito', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Robert', 'Arboleda', 2, 'Defensor', 'São Paulo', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Piero', 'Hincapié', 3, 'Defensor', 'Bayer Leverkusen', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Jackson', 'Porozo', 4, 'Defensor', 'Troyes', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Felix', 'Torres', 5, 'Defensor', 'Corinthians', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Pervis', 'Estupiñán', 13, 'Defensor', 'Brighton', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Diego', 'Palacios', 14, 'Defensor', 'Los Angeles FC', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Carlos', 'Gruezo', 6, 'Centrocampista', 'San Lorenzo', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Romario', 'Ibarra', 8, 'Centrocampista', 'Pachuca', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Leonardo', 'Campana', 10, 'Centrocampista', 'Inter Miami', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Ángel', 'Mena', 15, 'Centrocampista', 'León', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Alan', 'Franco', 7, 'Delantero', 'Talleres', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Enner', 'Valencia', 9, 'Delantero', 'Internacional', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Kendry', 'Páez', 11, 'Delantero', 'Independiente', 17, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Jordy', 'Caicedo', 18, 'Delantero', 'Corinthians', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Kevin', 'Rodríguez', 17, 'Delantero', 'Imbabura', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Joao', 'Ortiz', 16, 'Centrocampista', 'Independiente', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Jeremy', 'Sarmiento', 20, 'Centrocampista', 'Brentford', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Sebas', 'Méndez', 21, 'Centrocampista', 'Newell''s', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Danny', 'Luna', 22, 'Delantero', 'Vélez Sarsfield', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Willian', 'Pacho', 24, 'Defensor', 'PSV', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Gilmar', 'Napa', 25, 'Portero', 'Emelec', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Érick', 'Castillo', 19, 'Delantero', 'Barcelona SC', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ECU'), 'Xavier', 'Arreaga', 26, 'Defensor', 'Seattle Sounders', 29, false)
ON CONFLICT DO NOTHING;

-- NETHERLANDS
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Bart', 'Verbruggen', 1, 'Portero', 'Brighton', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Mark', 'Fleckken', 12, 'Portero', 'Brentford', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Justin', 'Bijlow', 23, 'Portero', 'Feyenoord', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Virgil', 'van Dijk', 2, 'Defensor', 'Liverpool', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Matthijs', 'de Ligt', 3, 'Defensor', 'Bayern Múnich', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Nathan', 'Aké', 4, 'Defensor', 'Manchester City', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Denzel', 'Dumfries', 5, 'Defensor', 'Inter Milán', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Xavi', 'Simons', 13, 'Defensor', 'RB Leipzig', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Micky', 'van de Ven', 14, 'Defensor', 'Tottenham', 22, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Marten', 'de Roon', 6, 'Centrocampista', 'Atalanta', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Cody', 'Gakpo', 8, 'Centrocampista', 'Liverpool', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Frenkie', 'de Jong', 10, 'Centrocampista', 'Barcelona', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Joey', 'Veerman', 15, 'Centrocampista', 'PSV', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Xavi', 'Simons', 7, 'Delantero', 'RB Leipzig', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Wout', 'Weghorst', 9, 'Delantero', 'TSG Hoffenheim', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Memphis', 'Depay', 11, 'Delantero', 'Corinthians', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Brian', 'Brobbey', 18, 'Delantero', 'Ajax', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Noa', 'Lang', 17, 'Delantero', 'PSV', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Mats', 'Wieffer', 16, 'Centrocampista', 'Brighton', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Ryan', 'Gravenberch', 20, 'Centrocampista', 'Liverpool', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Jerdy', 'Schouten', 21, 'Centrocampista', 'PSV', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Steven', 'Bergwijn', 22, 'Delantero', 'Ajax', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Daley', 'Blind', 24, 'Defensor', 'Girona', 33, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Lutsharel', 'Geertruida', 19, 'Defensor', 'RB Leipzig', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Kjell', 'Scherpen', 25, 'Portero', 'Sturm Graz', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NED'), 'Ian', 'Maatsen', 26, 'Defensor', 'Borussia Dortmund', 22, false)
ON CONFLICT DO NOTHING;
