-- =============================================
-- MUNDIALE AMBATO 2026 - PART 2: Teams 22-48
-- =============================================

-- JAPAN (22)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Zion', 'Suzuki', 1, 'Portero', 'París Saint-Germain', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Kosei', 'Tani', 12, 'Portero', 'Nagoya Grampus', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Keisuke', 'Osako', 23, 'Portero', 'Vissel Kobe', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Kōki', 'Machida', 2, 'Defensor', 'Genk', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Shōgo', 'Taniguchi', 3, 'Defensor', 'Gamba Osaka', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Hiroki', 'Ito', 4, 'Defensor', 'Mainz 05', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Yūto', 'Nagatomo', 5, 'Defensor', 'FC Tokyo', 38, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Takehiro', 'Tomiyasu', 13, 'Defensor', 'Arsenal', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Yūta', 'Nakayama', 14, 'Defensor', 'Huddersfield', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Wataru', 'Endō', 6, 'Centrocampista', 'Stuttgart', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Kaoru', 'Mitoma', 8, 'Centrocampista', 'Brighton', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Takumi', 'Minamino', 10, 'Centrocampista', 'Monaco', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Aō', 'Tanaka', 15, 'Centrocampista', 'Leeds United', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Junya', 'Itō', 7, 'Delantero', 'Stuttgart', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Ayase', 'Ueda', 9, 'Delantero', 'Feyenoord', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Daizen', 'Maeda', 11, 'Delantero', 'Celtic', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Mao', 'Hosoya', 18, 'Delantero', 'Kashima Antlers', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Ritsu', 'Dōan', 17, 'Delantero', 'Freiburg', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Reo', 'Hatate', 16, 'Centrocampista', 'Celtic', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Hidemasa', 'Morita', 20, 'Centrocampista', 'Sporting', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Kenta', 'Chiba', 21, 'Centrocampista', 'Shimizu S-Pulse', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Shūta', 'Tanaka', 22, 'Delantero', 'Darmstadt', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Kōki', 'Gotō', 24, 'Centrocampista', 'Yokohama Marinos', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Tsubasa', 'Nishi', 26, 'Portero', 'Avispa Fukuoka', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Miki', 'Yamane', 19, 'Defensor', 'Kawasaki Frontale', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'JPN'), 'Ryōta', 'Ōshima', 25, 'Centrocampista', 'Kawasaki Frontale', 27, false)
ON CONFLICT DO NOTHING;

-- TUNISIA (23)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Aymen', 'Mathlouthi', 1, 'Portero', 'Espérance', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Moez', 'Ben Cherifia', 12, 'Portero', 'Espérance', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Bechir', 'Ben Saïd', 23, 'Portero', 'Monastir', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Montassar', 'Talbi', 2, 'Defensor', 'Lorient', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Dylan', 'Bronn', 3, 'Defensor', 'Nantes', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Yassine', 'Meriah', 4, 'Defensor', 'Espérance', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Ali', 'Maâloul', 5, 'Defensor', 'Al-Ahly', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Hanni', 'Amamou', 13, 'Defensor', 'Étoile du Sahel', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Rami', 'Bzeek', 14, 'Defensor', 'Al-Arabi', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Ellyes', 'Skhiri', 6, 'Centrocampista', 'Köln', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Hannibal', 'Mejbri', 8, 'Centrocampista', 'Burnley', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Wahbi', 'Khazri', 10, 'Centrocampista', 'Montpellier', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Aïssa', 'Laïdouni', 15, 'Centrocampista', 'Ferencváros', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Youssef', 'Msakni', 7, 'Delantero', 'Al-Arabi', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Taha', 'Yassine', 9, 'Delantero', 'Espérance', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Bassem', 'Srarfi', 11, 'Delantero', 'Espérance', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Firas', 'Chaouat', 18, 'Delantero', 'Étoile du Sahel', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Saad', 'Bguir', 17, 'Delantero', 'Abha', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Ferjani', 'Sassi', 16, 'Centrocampista', 'Al-Duhail', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Mohamed', 'Ali Ben', 20, 'Centrocampista', 'Monastir', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Hamza', 'Mathlouthi', 21, 'Delantero', 'Espérance', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Naïm', 'Sliti', 22, 'Delantero', 'Al-Shamal', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Mortadha', 'Ben Ouanes', 24, 'Defensor', 'Étoile du Sahel', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Mouez', 'Hassan', 26, 'Portero', 'Club Africain', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Ali', 'Abdi', 19, 'Centrocampista', 'Lens', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'TUN'), 'Nader', 'Ghandri', 25, 'Defensor', 'Espérance', 29, false)
ON CONFLICT DO NOTHING;

-- SWEDEN (24)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Robin', 'Olsen', 1, 'Portero', 'Astana', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Kristoffer', 'Nordfeldt', 12, 'Portero', 'AIK', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Viktor', 'Johansson', 23, 'Portero', 'Rotherham', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Victor', 'Lindelöf', 2, 'Defensor', 'Manchester United', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Isak', 'Hien', 3, 'Defensor', 'Milan', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Ludvig', 'Augustinsson', 4, 'Defensor', 'Sevilla', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Gabriel', 'Gudmundsson', 5, 'Defensor', 'Lille', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Joakim', 'Nilsson', 13, 'Defensor', 'St. Pauli', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Carl', 'Starfelt', 14, 'Defensor', 'Celta Vigo', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Albin', 'Ekdal', 6, 'Centrocampista', 'Cagliari', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Emil', 'Forsberg', 8, 'Centrocampista', 'Tottenham', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Viktor', 'Claesson', 10, 'Centrocampista', 'Köln', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Jesper', 'Karlsson', 15, 'Centrocampista', 'Bologna', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Dejan', 'Kulusevski', 7, 'Delantero', 'Tottenham', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Alexander', 'Isak', 9, 'Delantero', 'Newcastle', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Anthony', 'Elanga', 11, 'Delantero', 'Nottingham Forest', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Gustav', 'Nilsson', 18, 'Delantero', 'Nantes', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Benjamin', 'Nygren', 17, 'Delantero', 'Nordsjælland', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Kristoffer', 'Olsson', 16, 'Centrocampista', 'Midtjylland', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Mattias', 'Svanberg', 20, 'Centrocampista', 'Wolfsburg', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Jens', 'Cajuste', 21, 'Centrocampista', 'Napoli', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Ken', 'Sema', 22, 'Delantero', 'Watford', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Joseph', 'Okumu', 24, 'Defensor', 'Reims', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'John', 'Gyökeres', 26, 'Delantero', 'Sporting', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Linus', 'Wahlqvist', 19, 'Defensor', 'Norrköping', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'SWE'), 'Oscar', 'Jansson', 25, 'Portero', 'Brann', 29, false)
ON CONFLICT DO NOTHING;

-- BELGIUM (25)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Thibaut', 'Courtois', 1, 'Portero', 'Real Madrid', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Matz', 'Sels', 12, 'Portero', 'Nottingham Forest', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Koen', 'Casteels', 23, 'Portero', 'Wolfsburg', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Wout', 'Faes', 2, 'Defensor', 'Leicester', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Arthur', 'Theate', 3, 'Defensor', 'Rennes', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Zeno', 'Debast', 4, 'Defensor', 'Anderlecht', 20, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Jan', 'Vertonghen', 5, 'Defensor', 'Anderlecht', 37, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Thomas', 'Meunier', 13, 'Defensor', 'Borussia Dortmund', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Maxime', 'De Bie', 14, 'Defensor', 'Genk', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Youri', 'Tielemans', 6, 'Centrocampista', 'Aston Villa', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Kevin', 'De Bruyne', 8, 'Centrocampista', 'Manchester City', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Romelu', 'Lukaku', 10, 'Centrocampista', 'Napoli', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Amadou', 'Onana', 15, 'Centrocampista', 'Villarreal', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Jérémy', 'Doku', 7, 'Delantero', 'Manchester City', 21, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Loïs', 'Openda', 9, 'Delantero', 'RB Leipzig', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Charles', 'De Ketelaere', 11, 'Delantero', 'Atalanta', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Leandro', 'Trossard', 18, 'Delantero', 'Arsenal', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Johan', 'Bakayoko', 17, 'Delantero', 'PSV', 22, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Hans', 'Vanaken', 16, 'Centrocampista', 'Club Brugge', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Axel', 'Witsel', 20, 'Centrocampista', 'Atalanta', 35, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Nicolas', 'Raskin', 21, 'Centrocampista', 'Rangers', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Dodi', 'Lukebakio', 22, 'Delantero', 'Sevilla', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Ameen', 'Al-Dakhil', 24, 'Defensor', 'Burnley', 22, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Thomas', 'Kaminski', 25, 'Portero', 'Luton', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Mike', 'Maignan', 19, 'Portero', 'Milan', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'BEL'), 'Alexis', 'Saelemaekers', 26, 'Delantero', 'Bologna', 24, false)
ON CONFLICT DO NOTHING;

-- EGYPT (26)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mohamed', 'El Shenawy', 1, 'Portero', 'Al-Ahly', 35, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mohamed', 'Abu Gabal', 12, 'Portero', 'Zamalek', 34, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mahmoud', 'Gamal', 23, 'Portero', 'Pyramids', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mohamed', 'Hany', 2, 'Defensor', 'Al-Ahly', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mohamed', 'Abdelmonem', 3, 'Defensor', 'Al-Ahly', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ahmed', 'Hegazi', 4, 'Defensor', 'Al-Ittihad', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ahmed', 'Fatihi', 5, 'Defensor', 'Zamalek', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ahmed', 'Abu Al-Fotouh', 13, 'Defensor', 'Al-Ahly', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Omar', 'Kamal', 14, 'Defensor', 'Pyramids', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Hamdy', 'Fathy', 6, 'Centrocampista', 'Al-Ahly', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Trézéguet', 'Hassan', 8, 'Centrocampista', 'Kasimpaşa', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mohamed', 'Salah', 10, 'Centrocampista', 'Liverpool', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Marwan', 'Attia', 15, 'Centrocampista', 'Al-Ahly', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Omar', 'Marmoush', 7, 'Delantero', 'Manchester City', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mostafa', 'Mohamed', 9, 'Delantero', 'Al-Ahly', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ahmed', 'Sayed', 11, 'Delantero', 'Pyramids', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ahmed', 'Hassan', 18, 'Delantero', 'Zamalek', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ibrahim', 'Adel', 17, 'Delantero', 'Pyramids', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mohamed', 'Elneny', 16, 'Centrocampista', 'Al-Ahly', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mahmoud', 'Hassan', 20, 'Centrocampista', 'Pyramids', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Emam', 'Ashour', 21, 'Centrocampista', 'Al-Ahly', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ahmed', 'Yasser', 22, 'Delantero', 'Zamalek', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ali', 'Gaber', 24, 'Defensor', 'Pyramids', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'El', 'Shenawy', 26, 'Portero', 'Al-Ittihad', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Ahmed', 'Koka', 19, 'Delantero', 'Al-Ahly', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'EGY'), 'Mahmoud', 'Kahraba', 25, 'Delantero', 'Al-Ahly', 30, false)
ON CONFLICT DO NOTHING;

-- IRAN (27)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Alireza', 'Beiranvand', 1, 'Portero', 'Tractor', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Payam', 'Niazmand', 12, 'Portero', 'Sepahan', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Hossein', 'Hosseini', 23, 'Portero', 'Esteghlal', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Milad', 'Mohammadi', 2, 'Defensor', 'Persepolis', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Hossein', 'Kanani', 3, 'Defensor', 'Persepolis', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Shoja', 'Khalilzadeh', 4, 'Defensor', 'Tractor', 35, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Milad', 'Sarlahk', 5, 'Defensor', 'Sepahan', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Saleh', 'Hardani', 13, 'Defensor', 'Esteghlal', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Abolfazl', 'Jalali', 14, 'Defensor', 'Esteghlal', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Saeid', 'Ezatolahi', 6, 'Centrocampista', 'Vejle', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Alireza', 'Jahanbakhsh', 8, 'Centrocampista', 'Feyenoord', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Mehdi', 'Taremi', 10, 'Centrocampista', 'Inter Milán', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Omid', 'Ebrahimi', 15, 'Centrocampista', 'Esteghlal', 36, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Sardar', 'Azmoun', 7, 'Delantero', 'Shabab Al-Ahli', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Karim', 'Ansarifard', 9, 'Delantero', 'Esteghlal', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Ali', 'Gholizadeh', 11, 'Delantero', 'Charleroi', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Mehdi', 'Ghayedi', 18, 'Delantero', 'Esteghlal', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Ali', 'Alipour', 17, 'Delantero', 'Al-Arabi', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Ahmad', 'Nourollahi', 16, 'Centrocampista', 'Tractor', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Vahid', 'Amiri', 20, 'Centrocampista', 'Persepolis', 36, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Mohammad', 'Mohebi', 21, 'Delantero', 'Rostov', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Mehdi', 'Torabi', 22, 'Delantero', 'Persepolis', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Ramin', 'Rezaeian', 24, 'Defensor', 'Sepahan', 33, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Amir', 'Abedzadeh', 25, 'Portero', 'Esteghlal', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Majid', 'Hosseini', 19, 'Defensor', 'Kayserispor', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'IRN'), 'Rouzbeh', 'Cheshmi', 26, 'Defensor', 'Esteghlal', 31, false)
ON CONFLICT DO NOTHING;

-- NEW ZEALAND (28)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Max', 'Crocombe', 1, 'Portero', 'Grimsby Town', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Alex', 'Paulsen', 12, 'Portero', 'Leyton Orient', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Oliver', 'Sail', 23, 'Portero', 'Perth Glory', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Winston', 'Reid', 2, 'Defensor', 'Wellington Phoenix', 35, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Liberato', 'Cacace', 3, 'Defensor', 'Empoli', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Tommy', 'Smith', 4, 'Defensor', 'Columbus Crew', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Michael', 'Boxall', 5, 'Defensor', 'Minnesota United', 35, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Tim', 'Payne', 13, 'Defensor', 'Wellington Phoenix', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Nando', 'Pijnaker', 14, 'Defensor', 'Shamrock Rovers', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Joe', 'Bell', 6, 'Centrocampista', 'Viking', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Marko', 'Stamenic', 8, 'Centrocampista', 'Copenhagen', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Matthew', 'Garbutt', 10, 'Centrocampista', 'Wellington Phoenix', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Clayton', 'Lewis', 15, 'Centrocampista', 'Wellington Phoenix', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Chris', 'Wood', 7, 'Delantero', 'Nottingham Forest', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Kosta', 'Barbarouses', 9, 'Delantero', 'Wellington Phoenix', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Elijah', 'Just', 11, 'Delantero', 'Heerenveen', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Ben', 'Waine', 18, 'Delantero', 'Plymouth Argyle', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Alex', 'Greive', 17, 'Delantero', 'St. Mirren', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Bill', 'Tuiloma', 16, 'Centrocampista', 'Portland Timbers', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Dane', 'Ingham', 20, 'Centrocampista', 'Macarthur FC', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Ben', 'Old', 21, 'Delantero', 'Brisbane Roar', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Logan', 'Rogerson', 22, 'Delantero', 'Auckland FC', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Michael', 'Woud', 24, 'Portero', 'Auckland FC', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'James', 'McGarry', 26, 'Defensor', 'Auckland FC', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Callan', 'Elliot', 19, 'Centrocampista', 'Wellington Phoenix', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'NZL'), 'Francis', 'de Vries', 25, 'Defensor', 'Wellington Phoenix', 29, false)
ON CONFLICT DO NOTHING;

-- SPAIN (29)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Unai', 'Simón', 1, 'Portero', 'Athletic Bilbao', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'David', 'Raya', 12, 'Portero', 'Arsenal', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Robert', 'Sánchez', 23, 'Portero', 'Chelsea', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Dani', 'Carvajal', 2, 'Defensor', 'Real Madrid', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Robin', 'Le Normand', 3, 'Defensor', 'Atlético Madrid', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Aymeric', 'Laporte', 4, 'Defensor', 'Al-Nassr', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Marc', 'Cucurella', 5, 'Defensor', 'Chelsea', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Nacho', 'Fernández', 13, 'Defensor', 'Al-Qadsiah', 34, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Alejandro', 'Grimaldo', 14, 'Defensor', 'Bayer Leverkusen', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Rodri', 'Hernández', 6, 'Centrocampista', 'Manchester City', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Dani', 'Olmo', 8, 'Centrocampista', 'Barcelona', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Lamine', 'Yamal', 10, 'Centrocampista', 'Barcelona', 16, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Mikel', 'Merino', 15, 'Centrocampista', 'Arsenal', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Nico', 'Williams', 7, 'Delantero', 'Athletic Bilbao', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Álvaro', 'Morata', 9, 'Delantero', 'Galatasaray', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Ferran', 'Torres', 11, 'Delantero', 'Barcelona', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Mikel', 'Oyarzabal', 18, 'Delantero', 'Real Sociedad', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Ayoze', 'Pérez', 17, 'Delantero', 'Villarreal', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Martín', 'Zubimendi', 16, 'Centrocampista', 'Real Sociedad', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Fabián', 'Ruiz', 20, 'Centrocampista', 'Paris Saint-Germain', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Alejandro', 'Baena', 21, 'Centrocampista', 'Villarreal', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Samu', 'Omorodion', 22, 'Delantero', 'Porto', 21, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Pau', 'Cubarsí', 24, 'Defensor', 'Barcelona', 17, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Álex', 'Remiro', 25, 'Portero', 'Real Sociedad', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Jesús', 'Navas', 19, 'Defensor', 'Sevilla', 39, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'ESP'), 'Pau', 'Torres', 26, 'Defensor', 'Villarreal', 27, false)
ON CONFLICT DO NOTHING;

-- CAPE VERDE (30)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Vozinha', 'Borges', 1, 'Portero', 'Sabail', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Márcio', 'Rosa', 12, 'Portero', 'Santa Clara', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Elber', 'Evora', 23, 'Portero', 'Rio Ave', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Steven', 'Fortes', 2, 'Defensor', 'Pau', 30, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Roberto', 'Lopes', 3, 'Defensor', 'Sporting KC', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Diney', 'Borges', 4, 'Defensor', 'Pyunik', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Kenny', 'Rocha', 5, 'Defensor', 'Farense', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Jeffry', 'Fortes', 13, 'Defensor', 'Olympiakos', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Paulo', 'Monteiro', 14, 'Defensor', 'Moreirense', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Nando', 'Gomes', 6, 'Centrocampista', 'Arouca', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Jamiro', 'Monteiro', 8, 'Centrocampista', 'PAOK', 28, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Ryan', 'Mendes', 10, 'Centrocampista', 'Lille', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'João', 'Paulino', 15, 'Centrocampista', 'Vizela', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Gilson', 'Tavares', 7, 'Delantero', 'Hibernian', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Bebé', 'dos Santos', 9, 'Delantero', 'Rayo Vallecano', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Garry', 'Rodrigues', 11, 'Delantero', 'Al-Ittihad', 33, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Jovane', 'Cabral', 18, 'Delantero', 'Olympiakos', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Djaniny', 'Semedo', 17, 'Delantero', 'Al-Fateh', 33, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Patrick', 'Vieira', 16, 'Centrocampista', 'Sporting', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Deroy', 'Mbassa', 20, 'Centrocampista', 'Santa Clara', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Kelvin', 'Pires', 21, 'Delantero', 'Estoril', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Duo', 'Dai', 22, 'Delantero', 'Arouca', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Ricky', 'Gomes', 24, 'Defensor', 'Marítimo', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Bruno', 'Varela', 25, 'Portero', 'B-SAD', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Clé', 'Santos', 19, 'Centrocampista', 'Arouca', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'CPV'), 'Alinito', 'Gomes', 26, 'Delantero', 'Farense', 23, false)
ON CONFLICT DO NOTHING;

-- SAUDI ARABIA (31)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Mohammed', 'Al-Owais', 1, 'Portero', 'Al-Hilal', 32, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Nawaf', 'Al-Aqidi', 12, 'Portero', 'Al-Nassr', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Ahmed', 'Al-Kassar', 23, 'Portero', 'Al-Shabab', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Sultan', 'Al-Ghanam', 2, 'Defensor', 'Al-Nassr', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Awn', 'Al-Saluli', 3, 'Defensor', 'Al-Ittihad', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Ali', 'Al-Bulayhi', 4, 'Defensor', 'Al-Hilal', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Hassan', 'Tambakti', 5, 'Defensor', 'Al-Hilal', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Yasser', 'Al-Shahrani', 13, 'Defensor', 'Al-Hilal', 32, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Abdulrahman', 'Al-Obaid', 14, 'Defensor', 'Al-Nassr', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Salman', 'Al-Faraj', 6, 'Centrocampista', 'Al-Hilal', 34, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Salem', 'Al-Dawsari', 8, 'Centrocampista', 'Al-Hilal', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Firas', 'Al-Buraikan', 10, 'Centrocampista', 'Al-Ahli', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Abdullah', 'Otayf', 15, 'Centrocampista', 'Al-Shabab', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Abdullah', 'Al-Salem', 7, 'Delantero', 'Al-Fateh', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Sami', 'Al-Najei', 9, 'Delantero', 'Al-Qadsiah', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Saleh', 'Al-Shehri', 11, 'Delantero', 'Al-Hilal', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Abdulaziz', 'Al-Bishi', 18, 'Delantero', 'Al-Ittihad', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Hattan', 'Babalghith', 17, 'Delantero', 'Al-Wehda', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Nasser', 'Dosari', 16, 'Centrocampista', 'Al-Hilal', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Mohamed', 'Kanno', 20, 'Centrocampista', 'Al-Hilal', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Abdulrahman', 'Ghareeb', 21, 'Delantero', 'Al-Nassr', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Nawaf', 'Al-Abed', 22, 'Centrocampista', 'Al-Taawoun', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Ziyad', 'Al-Sahafi', 24, 'Defensor', 'Al-Ittihad', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Fawaz', 'Al-Qarni', 25, 'Portero', 'Al-Ittihad', 30, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Saad', 'Al-Mousa', 19, 'Defensor', 'Al-Ettifaq', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'KSA'), 'Mohammed', 'Sulaiman', 26, 'Delantero', 'Al-Raed', 24, false)
ON CONFLICT DO NOTHING;

-- URUGUAY (32)
INSERT INTO jugadores (seleccion_id, nombre, apellido, numero, posicion, club, edad, es_titular) VALUES
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Sergio', 'Rochet', 1, 'Portero', 'Internacional', 31, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Franco', 'Israel', 12, 'Portero', 'Vasco da Gama', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Randall', 'Rodríguez', 23, 'Portero', 'Peñarol', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Ronald', 'Araújo', 2, 'Defensor', 'Barcelona', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Sebastián', 'Cáceres', 3, 'Defensor', 'América', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'José', 'Giménez', 4, 'Defensor', 'Atlético Madrid', 29, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Matías', 'Viña', 5, 'Defensor', 'Flamengo', 26, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Nahitan', 'Nández', 13, 'Defensor', 'Cagliari', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Gonzalo', 'González', 14, 'Defensor', 'Tijuana', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Manuel', 'Ugarte', 6, 'Centrocampista', 'Paris Saint-Germain', 23, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Nicolás', 'De la Cruz', 8, 'Centrocampista', 'Flamengo', 27, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Federico', 'Valverde', 10, 'Centrocampista', 'Real Madrid', 25, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Giorgian', 'De Arrascaeta', 15, 'Centrocampista', 'Flamengo', 29, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Facundo', 'Pellistri', 7, 'Delantero', 'Panathinaikos', 22, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Luis', 'Suárez', 9, 'Delantero', 'Inter Miami', 37, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Darwin', 'Núñez', 11, 'Delantero', 'Liverpool', 24, true),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Agustín', 'Álvarez', 18, 'Delantero', 'Sassuolo', 23, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Maximiliano', 'Gómez', 17, 'Delantero', 'Celta Vigo', 27, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Lucas', 'Torreira', 16, 'Centrocampista', 'Galatasaray', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Matías', 'Olivera', 20, 'Defensor', 'Napoli', 26, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Brian', 'Rodríguez', 21, 'Delantero', 'América', 24, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Emiliano', 'Gómez', 22, 'Delantero', 'Peñarol', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Santiago', 'Mele', 24, 'Portero', 'Cerro Largo', 28, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Guillermo', 'Varela', 19, 'Defensor', 'Flamengo', 31, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Agustín', 'Canobbio', 25, 'Centrocampista', 'Internacional', 25, false),
((SELECT id FROM selecciones WHERE codigo_fifa = 'URU'), 'Christian', 'Olivera', 26, 'Delantero', 'Los Angeles FC', 23, false)
ON CONFLICT DO NOTHING;
